import { initDatabase } from './src/services/db.js';
import { generateVideo, cleanup } from './src/services/videoGenerator.js';
import { makeWASocket, useMultiFileAuthState, DisconnectReason } from 'baileys';
import { Boom } from '@hapi/boom';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

async function main() {
    await initDatabase();

    // Generate video
    const target = process.argv[2] || 'tips hemat energi';
    const start = Date.now();
    console.log('Generate video: ' + target);

    let result;
    try {
        result = await generateVideo(target, (msg) => {
            console.log('  [' + ((Date.now()-start)/1000).toFixed(0) + 's] ' + msg);
        });
        console.log('Video jadi: ' + result.title + ' (' + (fs.statSync(result.outputPath).size/1024/1024).toFixed(1) + 'MB)');
    } catch (e) {
        console.log('Generate gagal: ' + e.message);
        process.exit(1);
    }

    // Connect WA and send
    console.log('Login WhatsApp...');
    const { state, saveCreds } = await useMultiFileAuthState(path.join(__dirname, 'auth_session'));

    const sock = makeWASocket({
        auth: state,
        printQRInTerminal: false
    });

    sock.ev.on('creds.update', saveCreds);

    sock.ev.on('connection.update', async (update) => {
        const { connection, lastDisconnect } = update;
        if (connection === 'open') {
            console.log('WA terhubung!');

            // Send to target
            const jid = '6289671133560@s.whatsapp.net';
            const videoBuffer = fs.readFileSync(result.outputPath);

            console.log('Kirim video ke ' + jid + '...');
            await sock.sendMessage(jid, {
                video: videoBuffer,
                caption: result.title + '\n\nGenerated by Thirty'
            });
            console.log('Video terkirim!');

            // Cleanup
            cleanup(result.workDir);
            await sock.logout();
            process.exit(0);
        }

        if (connection === 'close') {
            const shouldReconnect = lastDisconnect?.error?.output?.statusCode !== DisconnectReason.loggedOut;
            console.log('WA disconnect, reconnect:', shouldReconnect);
            if (!shouldReconnect) process.exit(1);
        }
    });
}

main().catch(e => {
    console.log('Error:', e.message);
    process.exit(1);
});
