export default {
    name: 'gambar',
    title: 'Generate Gambar AI',
    description: 'Buat gambar dari teks menggunakan AI (Pollinations.ai)',
    commands: ['gambar', 'img', 'imagine', 'generate'],

    async handler(sock, remoteJid, args) {
        const prompt = args.join(' ').trim();
        if (!prompt) {
            await sock.sendMessage(remoteJid, {
                text: `🎨 *Generate Gambar AI*
Buat gambar dari deskripsi teks menggunakan AI.

*Contoh:*
• /gambar kucing lucu pakai topi
• /img pemandangan gunung di senja hari
• /generate logo keren futuristic biru

_Catatan: Butuh waktu beberapa detik untuk generate._`
            });
            return;
        }

        await sock.sendPresenceUpdate('composing', remoteJid);
        await sock.sendMessage(remoteJid, {
            text: `🎨 _Membuat gambar: "${prompt}"..._\n_Mohon tunggu beberapa detik..._`
        });

        try {
            // Pollinations.ai - free image generation, no API key
            const imageUrl = `https://image.pollinations.ai/prompt/${encodeURIComponent(prompt)}?width=1024&height=1024&nologo=true&model=flux`;

            // Fetch the image first to verify it works
            const response = await fetch(imageUrl, {
                signal: AbortSignal.timeout(30000),
            });

            if (!response.ok) {
                throw new Error(`API returned status ${response.status}`);
            }

            const buffer = Buffer.from(await response.arrayBuffer());

            await sock.sendMessage(remoteJid, {
                image: buffer,
                caption: `🎨 *${prompt}*\n\n_Generated by Pollinations.ai_`,
            });
        } catch (err) {
            console.error('Gambar Error:', err.message);
            await sock.sendMessage(remoteJid, {
                text: `❌ Gagal generate gambar.\nError: ${err.message}\n\nCoba dengan prompt yang lebih sederhana.`
            });
        }
    }
};
