import fs from 'fs';
import { generateVideo, isVideoJobRunning, cleanup } from '../services/videoGenerator.js';

export default {
    name: 'video',
    title: 'Buat Video',
    description: 'Generate video otomatis dari topik via AI + Pollinations + TTS + FFmpeg',
    commands: ['buatvideo', 'bv', 'video'],

    async handler(sock, remoteJid, args, context) {
        const topic = args.join(' ');
        if (!topic) {
            await sock.sendMessage(remoteJid, {
                text: 'Gunakan: /buatvideo [topik]\n\nContoh: /buatvideo cara kerja AI'
            });
            return;
        }

        if (isVideoJobRunning()) {
            await sock.sendMessage(remoteJid, {
                text: 'Masih ada video yang sedang digenerate. Tunggu selesai dulu ya!'
            });
            return;
        }

        await sock.sendMessage(remoteJid, {
            text: 'Mulai generate video...'
        });

        try {
            const result = await generateVideo(topic, async (progress) => {
                await sock.sendMessage(remoteJid, { text: progress });
            });
            global["last_video_path"] = result.outputPath;

            const videoBuffer = fs.readFileSync(result.outputPath);

            await sock.sendMessage(remoteJid, {
                video: videoBuffer,
                caption: result.title + '\n\nGenerated by Thirty'
            });

            cleanup(result.workDir);
        } catch (err) {
            await sock.sendMessage(remoteJid, {
                text: 'Gagal: ' + err.message
            });
        }
    }
};
