import { generateVideo, isVideoJobRunning, cleanup } from '../services/videoGenerator.js';

export default {
    name: 'video',
    title: 'Buat Video',
    description: 'Generate video otomatis dari topik via AI + Pollinations + TTS + FFmpeg',
    commands: ['buatvideo', 'bv', 'video'],

    async handler(sock, remoteJid, args, context) {
        const topic = args.join(' ');
        if (!topic) {
            await sock.sendMessage(remoteJid, {
                text: 'Gunakan: /buatvideo [topik]\n\nContoh: /buatvideo cara kerja AI'
            });
            return;
        }

        if (isVideoJobRunning()) {
            await sock.sendMessage(remoteJid, {
                text: 'Masih ada video yang sedang digenerate. Tunggu selesai dulu ya!'
            });
            return;
        }

        await sock.sendMessage(remoteJid, {
            text: 'Mulai generate video...'
        });

        try {
            let lastProgress = '';
            let lastSentAt = 0;
            const PROGRESS_INTERVAL_MS = parseInt(process.env.VIDEO_PROGRESS_INTERVAL_MS || '4000', 10);

            const result = await generateVideo(topic, async (progress) => {
                const now = Date.now();
                const shouldSend = progress !== lastProgress && (now - lastSentAt >= PROGRESS_INTERVAL_MS || /siap|gagal|selesai/i.test(progress));
                if (!shouldSend) return;
                lastProgress = progress;
                lastSentAt = now;
                await sock.sendMessage(remoteJid, { text: progress });
            });
            global["last_video_path"] = result.outputPath;

            await sock.sendMessage(remoteJid, {
                video: { url: result.outputPath },
                caption: result.title + '\n\nGenerated by Thirty'
            });

            cleanup(result.workDir);
        } catch (err) {
            await sock.sendMessage(remoteJid, {
                text: 'Gagal: ' + err.message
            });
        }
    }
};
